@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

HireME *-right-> "1" UniqueApplicationList
UniqueApplicationList -right-> Application

Application *--> CompanyName
Application *--> Role
Application *--> "0..1" Email
Application *--> "0..1" Website
Application *--> "0..1" Address
Application *--> Date
Application *--> Status
Application *--> "*" Tag
@enduml
